### ISSUE TITLE
Create stable version 2.0.2

### ISSUE THREAD

**Issue by anmol009a** [msankhala/parsehub-php#8]
The bug previously solved is not in the stable version, thus leading to problems during production.
Therefore, I request you to release a new version.
And also, please edit function return to "JSON" from "string of JSON" which is resulting in false positive error from IDE.

**Comment by msankhala** [comment]
Created a new version v2.0.2 which has the changes from https://github.com/msankhala/parsehub-php/pull/7 and created the next version v2.0.3 which has updated composer.lock file.
